### ISSUE TITLE
Capturing a rotated screen

### ISSUE THREAD

**Issue by bboyle1234** [stjeong/DxgiScreenCapture#1]
Dear @stjeong, 
Using what I learned from reading this repository, I was not able to capture a screenshot when the monitor is rotated, or "flipped". 
Here's a stackoverflow post I wrote about it: https://stackoverflow.com/questions/62752221/use-sharpdx-to-capture-screenshot-of-rotated-monitor
I believe this issue affects the code here too. I'd be very grateful if you can help solve the problem of capturing a rotated screen.

**Comment by bboyle1234** [comment]
How to rotate ("flip") a screen: 

![image](https://user-images.githubusercontent.com/1445862/86758009-8b2a3e80-c011-11ea-94ae-007d3c317047.png)

**Comment by stjeong** [comment]
I checked right before, capturing was still working when flipped. But, coordination will be different than before.

Let's assume the monitor is not flipped physically, but just setting "Display orientation" == "Portrait(flipped)".
Before the change, (0, 0) pixel is the top-left corner, but after the change, (0, 0) pixel is the right-top corner of that monitor.

(Tested, Windows 10 x64 2004 version, and LG IPS LED 24MA53 monitor.)

**Comment by bboyle1234** [comment]
ok, great that it worked for you. 
There is hope!! :) 
I tried to run your application without any modification, but nothing appeared in the display.

**Comment by bboyle1234** [comment]
Would you mind helping me with this? 
I can "pay you back" by helping write your code more efficiently - I'm very good at fast, efficient, correct and allocation-free c#, not so good at directX :)
My skype id is "benjaminboyle". Discord is "bboyle1234 #6006"

**Comment by stjeong** [comment]
You said "without any modification", then maybe capturing will be incorrect.

With this code,
https://github.com/stjeong/DxgiScreenCapture/blob/master/sample/WindowsFormsApp1/Form1.cs

try change this code,

            _screenCapture = new ScreenCapture(_viewBox, new System.Drawing.Rectangle(200, 200, 500, 500));

with,
 
            _screenCapture = new ScreenCapture(_viewBox, new System.Drawing.Rectangle(200, 200, 500, 500 ), CaptureSource.Monitor2);

The problem might be, your monitor #1 is disconnected, which doesn't contain (200, 200) ~ (500, 500) area.

**Comment by stjeong** [comment]
Sorry for not contacting with you. I'm not good at English.

**Comment by bboyle1234** [comment]
Capture loop reaches the first breakpoint but never gets to the second breakpoint: 

![image](https://user-images.githubusercontent.com/1445862/86881492-75be1e80-c0bc-11ea-883d-7e951d82d5c8.png)

**Comment by stjeong** [comment]
In my sample code, you have to press "ctrl + c" to capture. (Which means, you didn't read any code in https://github.com/stjeong/DxgiScreenCapture/blob/master/sample/WindowsFormsApp1/Form1.cs)

**Comment by stjeong** [comment]
Closed, if anything more, create new issue.
