### ISSUE TITLE
How to save screen capture?

### ISSUE THREAD

**Issue by lantongxue** [stjeong/DxgiScreenCapture#2]
How to save the screen capture to file ?

**Comment by stjeong** [comment]
You can see how to load raw RGB data from ScreenCapture at https://github.com/stjeong/DxgiScreenCapture/blob/master/sample/WindowsFormsApp1/Form1.cs

And, you can convert the raw data to Bitmap with this Q&A,

Convert RGB array to image in C#
; https://stackoverflow.com/questions/38989837/convert-rgb-array-to-image-in-c-sharp

**Comment by stjeong** [comment]
I added GetAsBitmap method in CapturedEventArgs.

You can see how to get as System.Drawing.Bitmap in https://github.com/stjeong/DxgiScreenCapture/blob/master/sample/WindowsFormsApp1/Form1.cs
(Line 32 ~ 33)
