### ISSUE TITLE
Could not load type 'DxgiScreenCapture.DXGIManager' from assembly 'DxgiScreenCapture

### ISSUE THREAD

**Issue by firepacket** [stjeong/DxgiScreenCapture#3]
How do you use this?

**Comment by stjeong** [comment]
Well... did you follow this?

1. Load DxgiCapture.sln
2. Build All
3. Set WindowsFormsApp1 as Startup project.
4. Run (F5)
5. Focus to WindowsFormsApp1 window, then hit Ctrl+C key to capture.

No errors detected.
